[pytest]

# пользовательские маркеры для группировки тестов
markers =

    # тесты, требующие проверки ревьюером
    need_review: marker for review tests

    # тесты для авторизованного пользователя
    user_test: marker for user tests

    # тесты для гостя (неавторизованный пользователь)
    login_guest: marker for login guest tests